// monster-database.dart

final List<Map<String, dynamic>> monsterDatabase = [
  {
    'name': 'Kirin rider',
    'hp': 72,
    'ac': 17,
    'initiative': 3,
    'nivel': 10,
    'xp': 0,
    'att': '1d8+7',
    'type': 'Japonés'
  },
  {
    'name': 'Kirin rider Tier 2',
    'hp': 132,
    'ac': 17,
    'initiative': 5,
    'nivel': 14,
    'xp': 0,
    'att': '2d8+7, El jefe tiene ataque especial de fuego (5d6 rayo de fuego seccion transversal circular de 10 ft de radio)',
    'type': 'Japonés'
  },
  {
    'name': 'Tengu',
    'hp': 15,
    'ac': 13,
    'initiative': 5,
    'xp': 0,
    'nivel': 3,
    'att': '1d6+2',
    'type': 'Japonés'
  },
  {
    'name': 'Glaceon',
    'hp': 70,
    'ac': 19,
    'nivel': 6,
    'xp': 0,
    'initiative': 5,
    'att': 'Mordisco gélido +9 (1d8+4 + 1d6 frío)',
    'movs': 'Ice Beam (4d6 frío); Blizzard (área 15ft, 3d6 frío + ralentiza); Hailstorm (2d6 frío/turno); Mirror Coat (1/encuentro)',
    'type': 'Pokémon'
  },
  {
    'name': 'Flareon',
    'hp': 75,
    'ac': 20,
    'nivel': 6,
    'xp': 0,
    'initiative': 5,
    'att': 'Mordisco ígneo +10 (1d10+5 + 1d6 fuego)',
    'movs': 'Flamethrower (4d6 fuego); Fire Spin (1d6/turno); Overheat (5d6, queda fatigado); Will-o-Wisp (quemadura)',
    'type': 'Pokémon'
  },
  {
    'name': 'Vaporeon',
    'hp': 90,
    'ac': 19,
    'nivel': 7,
    'xp': 0,
    'initiative': 5,
    'att': 'Mordisco acuático +9 (1d8+4 + 1d6 ácido)',
    'movs': 'Hydro Pump (5d6); Surf (3d6 área 20ft); Acid Armor (+3 CA por 3 turnos); Aqua Ring (cura 5hp/turno)',
    'type': 'Pokémon'
  },
  {
    'name': 'Jolteon',
    'hp': 65,
    'ac': 21,
    'nivel': 6,
    'xp': 0,
    'initiative': 5,
    'att': 'Mordisco eléctrico +9 (1d8+4 + 1d6 eléctrico)',
    'movs': 'Thunderbolt (4d6 eléctrico); Thunder Wave (parálisis 1d3 turnos); Volt Switch (ataque + reposicionarse); Discharge (área 10ft, 3d6 eléctrico)',
    'type': 'Pokémon'
  },
  {
    'name': 'Leafeon',
    'hp': 80,
    'ac': 19,
    'nivel': 6,
    'xp': 0,
    'initiative': 5,
    'att': 'Mordisco con hojas +9 (1d10+4 + 1d6 cortante)',
    'movs': 'Leaf Blade (2d8 crítico 19–20); Solar Beam (6d6, requiere cargar); Synthesis (cura 15hp); Grass Knot (derriba)',
    'type': 'Pokémon'
  },
  {
    'name': 'Umbreon',
    'hp': 90,
    'ac': 21,
    'nivel': 7,
    'xp': 0,
    'initiative': 5,
    'att': 'Mordisco sombrío +9 (1d8+4 + 1d6 necrótico)',
    'movs': 'Dark Pulse (4d6 necrótico área 15ft); Confuse Ray (confusión 1d3 turnos); Moonlight (cura 15hp); Curse (+2 daño, –2 AC)',
    'type': 'Pokémon'
  },
  {
    'name': 'Espeon',
    'hp': 70,
    'ac': 18,
    'nivel': 6,
    'xp': 0,
    'initiative': 5,
    'att': 'Mordisco psíquico +8 (1d6+4 + 1d6 psíquico)',
    'movs': 'Psychic (4d6 + empuja); Future Sight (5d6 explota en 2 turnos); Reflect (reduce daño físico en grupo); Morning Sun (cura 15hp)',
    'type': 'Pokémon'
  },
  {
    'name': 'Sylveon',
    'hp': 80,
    'ac': 20,
    'nivel': 7,
    'xp': 0,
    'initiative': 5,
    'att': 'Mordisco feérico +9 (1d8+4 + 1d6 radiante)',
    'movs': 'Moonblast (4d6 radiante, –2 daño enemigo); Charm (–2 ataque enemigo); Dazzling Gleam (área 15ft, 3d6 radiante); Heal Bell (cura condiciones)',
    'type': 'Pokémon'
  },
  {
    'name': 'Mokumokuren',
    'hp': 55,
    'ac': 17,
    'nivel': 5,
    'xp': 0,
    'initiative': 4,
    'att': 'Mirada hipnótica +8 (1d8+2 psíquico)',
    'movs': 'Ojo Vigilante (detecta invisibilidad); Lluvia de Ojos (área 10ft, 2d6 daño psíquico); Parpadeo Ilusorio (desvía un ataque); Grito de los Mil Ojos (confunde a todos en 20ft, 1/encuentro)',
    'type': 'Japonés'
  },
  {
    'name': 'Elemental de Aire Pequeño',
    'type': 'Elemental',
    'hp': 13,
    'ac': 17,
    'nivel': 1,
    'xp': 0,
    'initiative': 5,
    'att': 'Golpe +4 (1d6)',
    'movs': 'Viento Rápido (ignora terreno difícil); Empuje de Aire (derriba a un enemigo)'
  },
  {
    'name': 'Elemental de Aire Mediano',
    'type': 'Elemental',
    'hp': 30,
    'ac': 18,
    'nivel': 3,
    'xp': 0,
    'initiative': 7,
    'att': 'Golpe +7 (1d8+1)',
    'movs': 'Torbellino (área 10ft, 2d6 daño y derriba); Viento Rápido'
  },
  {
    'name': 'Elemental de Aire Grande',
    'type': 'Elemental',
    'hp': 60,
    'ac': 20,
    'nivel': 5,
    'xp': 0,
    'initiative': 9,
    'att': 'Golpe +12 (2d6+4)',
    'movs': 'Torbellino Mayor (área 15ft, 3d6 daño y derriba); Viento Huracanado (empuja 20ft)'
  },
  {
    'name': 'Elemental de Aire Enorme',
    'type': 'Elemental',
    'hp': 95,
    'ac': 22,
    'nivel': 9,
    'xp': 0,
    'initiative': 11,
    'att': 'Golpe +18 (2d8+7)',
    'movs': 'Torbellino Gigante (área 20ft, 4d6 daño y derriba); Viento Devastador (derriba a todos en 30ft)'
  },
  {
    'name': 'Elemental de Aire Colosal',
    'type': 'Elemental',
    'hp': 152,
    'ac': 26,
    'nivel': 13,
    'xp': 0,
    'initiative': 13,
    'att': 'Golpe +26 (4d6+10)',
    'movs': 'Torbellino Cataclísmico (área 30ft, 8d6 daño y derriba); Viento Imparable (derriba y empuja a todos en 40ft)'
  },
  {
    'name': 'Elemental de Fuego Pequeño',
    'type': 'Elemental',
    'hp': 11,
    'ac': 17,
    'nivel': 1,
    'xp': 0,
    'initiative': 7,
    'att': 'Golpe +4 (1d6 fuego)',
    'movs': 'Cuerpo Ígneo (daño 1d4 al contacto); Llama Rápida (mueve el doble)'
  },
  {
    'name': 'Elemental de Fuego Mediano',
    'type': 'Elemental',
    'hp': 27,
    'ac': 17,
    'nivel': 3,
    'xp': 0,
    'initiative': 9,
    'att': 'Golpe +7 (1d8+1 fuego)',
    'movs': 'Explosión Ígnea (área 10ft, 2d6 fuego); Cuerpo Ígneo'
  },
  {
    'name': 'Elemental de Fuego Grande',
    'type': 'Elemental',
    'hp': 58,
    'ac': 19,
    'nivel': 5,
    'xp': 0,
    'initiative': 11,
    'att': 'Golpe +12 (2d6+4 fuego)',
    'movs': 'Explosión Mayor (área 15ft, 3d6 fuego); Cuerpo Ígneo'
  },
  {
    'name': 'Elemental de Fuego Enorme',
    'type': 'Elemental',
    'hp': 102,
    'ac': 21,
    'nivel': 9,
    'xp': 0,
    'initiative': 13,
    'att': 'Golpe +18 (2d8+7 fuego)',
    'movs': 'Explosión Gigante (área 20ft, 4d6 fuego); Cuerpo Ígneo'
  },
  {
    'name': 'Elemental de Fuego Colosal',
    'type': 'Elemental',
    'hp': 168,
    'ac': 25,
    'nivel': 13,
    'xp': 0,
    'initiative': 15,
    'att': 'Golpe +26 (4d6+10 fuego)',
    'movs': 'Explosión Cataclísmica (área 30ft, 8d6 fuego); Cuerpo Ígneo'
  },
  {
    'name': 'Elemental de Tierra Pequeño',
    'type': 'Elemental',
    'hp': 17,
    'ac': 17,
    'nivel': 1,
    'xp': 0,
    'initiative': -1,
    'att': 'Golpe +6 (1d8+1)',
    'movs': 'Excavar (ignora terreno); Golpe Aturdidor (aturde 1 turno)'
  },
  {
    'name': 'Elemental de Tierra Mediano',
    'type': 'Elemental',
    'hp': 34,
    'ac': 18,
    'nivel': 3,
    'xp': 0,
    'initiative': 1,
    'att': 'Golpe +9 (2d6+3)',
    'movs': 'Excavar Rápido; Golpe Aturdidor'
  },
  {
    'name': 'Elemental de Tierra Grande',
    'type': 'Elemental',
    'hp': 68,
    'ac': 20,
    'nivel': 5,
    'xp': 0,
    'initiative': 3,
    'att': 'Golpe +14 (2d8+7)',
    'movs': 'Terremoto (área 15ft, 3d6 daño y derriba); Excavar Rápido'
  },
  {
    'name': 'Elemental de Tierra Enorme',
    'type': 'Elemental',
    'hp': 102,
    'ac': 22,
    'nivel': 9,
    'xp': 0,
    'initiative': 5,
    'att': 'Golpe +20 (2d10+10)',
    'movs': 'Terremoto Mayor (área 20ft, 4d6 daño y derriba); Excavar Rápido'
  },
  {
    'name': 'Elemental de Tierra Colosal',
    'type': 'Elemental',
    'hp': 152,
    'ac': 26,
    'nivel': 13,
    'xp': 0,
    'initiative': 7,
    'att': 'Golpe +28 (4d8+14)',
    'movs': 'Terremoto Cataclísmico (área 30ft, 8d6 daño y derriba); Excavar Rápido'
  },
  {
    'name': 'Elemental de Agua Pequeño',
    'type': 'Elemental',
    'hp': 13,
    'ac': 17,
    'nivel': 1,
    'xp': 0,
    'initiative': 1,
    'att': 'Golpe +4 (1d6)',
    'movs': 'Forma Líquida (ignora obstáculos); Ola (derriba a un enemigo)'
  },
  {
    'name': 'Elemental de Agua Mediano',
    'type': 'Elemental',
    'hp': 30,
    'ac': 18,
    'nivel': 3,
    'xp': 0,
    'initiative': 3,
    'att': 'Golpe +7 (1d8+1)',
    'movs': 'Ola Mayor (área 10ft, 2d6 daño y derriba); Forma Líquida'
  },
  {
    'name': 'Elemental de Agua Grande',
    'type': 'Elemental',
    'hp': 60,
    'ac': 20,
    'nivel': 5,
    'xp': 0,
    'initiative': 5,
    'att': 'Golpe +12 (2d6+4)',
    'movs': 'Ola Gigante (área 15ft, 3d6 daño y derriba); Forma Líquida'
  },
  {
    'name': 'Elemental de Agua Enorme',
    'type': 'Elemental',
    'hp': 95,
    'ac': 22,
    'nivel': 9,
    'xp': 0,
    'initiative': 7,
    'att': 'Golpe +18 (2d8+7)',
    'movs': 'Ola Cataclísmica (área 20ft, 4d6 daño y derriba); Forma Líquida'
  },
  {
    'name': 'Elemental de Agua Colosal',
    'type': 'Elemental',
    'hp': 152,
    'ac': 26,
    'nivel': 13,
    'xp': 0,
    'initiative': 9,
    'att': 'Golpe +26 (4d6+10)',
    'movs': 'Ola Apocalíptica (área 30ft, 8d6 daño y derriba); Forma Líquida'
  },
  // Elementales de Hielo
  {
    'name': 'Elemental de Hielo Pequeño',
    'type': 'Elemental',
    'hp': 14,
    'ac': 17,
    'nivel': 1,
    'xp': 0,
    'initiative': 3,
    'att': 'Golpe +4 (1d6 frío)',
    'movs': 'Aura Helada (ralentiza 5ft); Congelación Menor (1d4 frío)'
  },
  {
    'name': 'Elemental de Hielo Mediano',
    'type': 'Elemental',
    'hp': 32,
    'ac': 18,
    'nivel': 3,
    'xp': 0,
    'initiative': 5,
    'att': 'Golpe +7 (1d8+1 frío)',
    'movs': 'Aura Helada; Congelación (2d4 frío y ralentiza)'
  },
  {
    'name': 'Elemental de Hielo Grande',
    'type': 'Elemental',
    'hp': 65,
    'ac': 20,
    'nivel': 5,
    'xp': 0,
    'initiative': 7,
    'att': 'Golpe +12 (2d6+4 frío)',
    'movs': 'Aura Helada Mayor; Congelación Mayor (3d4 frío y ralentiza)'
  },
  {
    'name': 'Elemental de Hielo Enorme',
    'type': 'Elemental',
    'hp': 110,
    'ac': 22,
    'nivel': 9,
    'xp': 0,
    'initiative': 9,
    'att': 'Golpe +18 (2d8+7 frío)',
    'movs': 'Aura Glacial (ralentiza y daña 2d6 frío); Congelación Total (paraliza 1 turno)'
  },
  {
    'name': 'Elemental de Hielo Colosal',
    'type': 'Elemental',
    'hp': 170,
    'ac': 26,
    'nivel': 13,
    'xp': 0,
    'initiative': 11,
    'att': 'Golpe +26 (4d6+10 frío)',
    'movs': 'Tormenta Glacial (área 30ft, 8d6 frío y ralentiza); Congelación Total'
  },
  // Elementales de Ácido
  {
    'name': 'Elemental de Ácido Pequeño',
    'type': 'Elemental',
    'hp': 12,
    'ac': 16,
    'nivel': 1,
    'xp': 0,
    'initiative': 2,
    'att': 'Golpe +4 (1d6 ácido)',
    'movs': 'Cuerpo Corrosivo (daño 1d4 al contacto); Salpicadura Ácida (1d6 ácido)'
  },
  {
    'name': 'Elemental de Ácido Mediano',
    'type': 'Elemental',
    'hp': 28,
    'ac': 17,
    'nivel': 3,
    'xp': 0,
    'initiative': 4,
    'att': 'Golpe +7 (1d8+1 ácido)',
    'movs': 'Cuerpo Corrosivo; Salpicadura Ácida Mayor (2d6 ácido)'
  },
  {
    'name': 'Elemental de Ácido Grande',
    'type': 'Elemental',
    'hp': 60,
    'ac': 19,
    'nivel': 5,
    'xp': 0,
    'initiative': 6,
    'att': 'Golpe +12 (2d6+4 ácido)',
    'movs': 'Cuerpo Corrosivo Mayor; Lluvia Ácida (área 10ft, 2d6 ácido)'
  },
  {
    'name': 'Elemental de Ácido Enorme',
    'type': 'Elemental',
    'hp': 100,
    'ac': 21,
    'nivel': 9,
    'xp': 0,
    'initiative': 8,
    'att': 'Golpe +18 (2d8+7 ácido)',
    'movs': 'Cuerpo Corrosivo Gigante; Lluvia Ácida Mayor (área 20ft, 4d6 ácido)'
  },
  {
    'name': 'Elemental de Ácido Colosal',
    'type': 'Elemental',
    'hp': 160,
    'ac': 25,
    'nivel': 13,
    'xp': 0,
    'initiative': 10,
    'att': 'Golpe +26 (4d6+10 ácido)',
    'movs': 'Tormenta Ácida (área 30ft, 8d6 ácido); Cuerpo Corrosivo Cataclísmico'
  },
  // Elementales de Sombra
  {
    'name': 'Elemental de Sombra Pequeño',
    'type': 'Elemental',
    'hp': 13,
    'ac': 17,
    'nivel': 1,
    'xp': 0,
    'initiative': 6,
    'att': 'Golpe +4 (1d6 necrótico)',
    'movs': 'Oscuridad Menor (área 10ft); Toque Sombrío (reduce daño enemigo)'
  },
  {
    'name': 'Elemental de Sombra Mediano',
    'type': 'Elemental',
    'hp': 30,
    'ac': 18,
    'nivel': 3,
    'xp': 0,
    'initiative': 8,
    'att': 'Golpe +7 (1d8+1 necrótico)',
    'movs': 'Oscuridad Mayor (área 20ft); Toque Sombrío'
  },
  {
    'name': 'Elemental de Sombra Grande',
    'type': 'Elemental',
    'hp': 62,
    'ac': 20,
    'nivel': 5,
    'xp': 0,
    'initiative': 10,
    'att': 'Golpe +12 (2d6+4 necrótico)',
    'movs': 'Oscuridad Total (área 30ft); Toque Sombrío Mayor (reduce daño y AC)'
  },
  {
    'name': 'Elemental de Sombra Enorme',
    'type': 'Elemental',
    'hp': 98,
    'ac': 22,
    'nivel': 9,
    'xp': 0,
    'initiative': 12,
    'att': 'Golpe +18 (2d8+7 necrótico)',
    'movs': 'Oscuridad Absoluta (área 40ft); Toque Sombrío Cataclísmico'
  },
  {
    'name': 'Elemental de Sombra Colosal',
    'type': 'Elemental',
    'hp': 155,
    'ac': 26,
    'nivel': 13,
    'xp': 0,
    'initiative': 14,
    'att': 'Golpe +26 (4d6+10 necrótico)',
    'movs': 'Tormenta de Sombras (área 60ft, 8d6 necrótico); Toque Sombrío Cataclísmico'
  },
  // Elementales de Luz
  {
    'name': 'Elemental de Luz Pequeño',
    'type': 'Elemental',
    'hp': 12,
    'ac': 18,
    'nivel': 1,
    'xp': 0,
    'initiative': 7,
    'att': 'Golpe +4 (1d6 radiante)',
    'movs': 'Destello (cegar 1 turno); Luz Menor (área 10ft)'
  },
  {
    'name': 'Elemental de Luz Mediano',
    'type': 'Elemental',
    'hp': 28,
    'ac': 19,
    'nivel': 3,
    'xp': 0,
    'initiative': 9,
    'att': 'Golpe +7 (1d8+1 radiante)',
    'movs': 'Destello Mayor (cegar 2 turnos); Luz Mayor (área 20ft)'
  },
  {
    'name': 'Elemental de Luz Grande',
    'type': 'Elemental',
    'hp': 60,
    'ac': 21,
    'nivel': 5,
    'xp': 0,
    'initiative': 11,
    'att': 'Golpe +12 (2d6+4 radiante)',
    'movs': 'Destello Total (cegar 3 turnos); Luz Total (área 30ft)'
  },
  {
    'name': 'Elemental de Luz Enorme',
    'type': 'Elemental',
    'hp': 100,
    'ac': 23,
    'nivel': 9,
    'xp': 0,
    'initiative': 13,
    'att': 'Golpe +18 (2d8+7 radiante)',
    'movs': 'Destello Absoluto (cegar 4 turnos); Luz Absoluta (área 40ft)'
  },
  {
    'name': 'Elemental de Luz Colosal',
    'type': 'Elemental',
    'hp': 160,
    'ac': 27,
    'nivel': 13,
    'xp': 0,
    'initiative': 15,
    'att': 'Golpe +26 (4d6+10 radiante)',
    'movs': 'Tormenta de Luz (área 60ft, 8d6 radiante); Destello Cataclísmico'
  },
  // Elementales de Planta
  {
    'name': 'Elemental de Planta Pequeño',
    'type': 'Elemental',
    'hp': 15,
    'ac': 16,
    'nivel': 1,
    'xp': 0,
    'initiative': 2,
    'att': 'Golpe +4 (1d6 cortante)',
    'movs': 'Enredar (ralentiza); Espinas (1d4 daño al atacante)'
  },
  {
    'name': 'Elemental de Planta Mediano',
    'type': 'Elemental',
    'hp': 32,
    'ac': 17,
    'nivel': 3,
    'xp': 0,
    'initiative': 4,
    'att': 'Golpe +7 (1d8+1 cortante)',
    'movs': 'Enredar Mayor; Espinas Mayores (1d6 daño al atacante)'
  },
  {
    'name': 'Elemental de Planta Grande',
    'type': 'Elemental',
    'hp': 65,
    'ac': 19,
    'nivel': 5,
    'xp': 0,
    'initiative': 6,
    'att': 'Golpe +12 (2d6+4 cortante)',
    'movs': 'Enredar Total; Espinas Gigantes (2d4 daño al atacante)'
  },
  {
    'name': 'Elemental de Planta Enorme',
    'type': 'Elemental',
    'hp': 110,
    'ac': 21,
    'nivel': 9,
    'xp': 0,
    'initiative': 8,
    'att': 'Golpe +18 (2d8+7 cortante)',
    'movs': 'Enredar Cataclísmico; Espinas Cataclísmicas (3d4 daño al atacante)'
  },
  {
    'name': 'Elemental de Planta Colosal',
    'type': 'Elemental',
    'hp': 170,
    'ac': 25,
    'nivel': 13,
    'xp': 0,
    'initiative': 10,
    'att': 'Golpe +26 (4d6+10 cortante)',
    'movs': 'Tormenta de Espinas (área 30ft, 8d6 cortante); Enredar Cataclísmico'
  },
  // Elementales de Metal
  {
    'name': 'Elemental de Metal Pequeño',
    'type': 'Elemental',
    'hp': 18,
    'ac': 18,
    'nivel': 1,
    'xp': 0,
    'initiative': 0,
    'att': 'Golpe +4 (1d6 contundente)',
    'movs': 'Cuerpo Metálico (resistencia al daño); Magnetismo Menor (desarma armas pequeñas)'
  },
  {
    'name': 'Elemental de Metal Mediano',
    'type': 'Elemental',
    'hp': 36,
    'ac': 19,
    'nivel': 3,
    'xp': 0,
    'initiative': 2,
    'att': 'Golpe +7 (1d8+1 contundente)',
    'movs': 'Cuerpo Metálico Mayor; Magnetismo (desarma armas medianas)'
  },
  {
    'name': 'Elemental de Metal Grande',
    'type': 'Elemental',
    'hp': 72,
    'ac': 21,
    'nivel': 5,
    'xp': 0,
    'initiative': 4,
    'att': 'Golpe +12 (2d6+4 contundente)',
    'movs': 'Cuerpo Metálico Gigante; Magnetismo Mayor (desarma armas grandes)'
  },
  {
    'name': 'Elemental de Metal Enorme',
    'type': 'Elemental',
    'hp': 120,
    'ac': 23,
    'nivel': 9,
    'xp': 0,
    'initiative': 6,
    'att': 'Golpe +18 (2d8+7 contundente)',
    'movs': 'Cuerpo Metálico Cataclísmico; Magnetismo Cataclísmico (desarma a todos en 20ft)'
  },
  {
    'name': 'Elemental de Metal Colosal',
    'type': 'Elemental',
    'hp': 180,
    'ac': 27,
    'nivel': 13,
    'xp': 0,
    'initiative': 8,
    'att': 'Golpe +26 (4d6+10 contundente)',
    'movs': 'Tormenta Metálica (área 30ft, 8d6 contundente); Magnetismo Cataclísmico'
  },
  // Elementales de Rayo
  {
    'name': 'Elemental de Rayo Pequeño',
    'type': 'Elemental',
    'hp': 12,
    'ac': 17,
    'nivel': 1,
    'xp': 0,
    'initiative': 8,
    'att': 'Golpe +4 (1d6 eléctrico)',
    'movs': 'Descarga Menor (1d4 eléctrico); Cuerpo Eléctrico (daño al atacante)'
  },
  {
    'name': 'Elemental de Rayo Mediano',
    'type': 'Elemental',
    'hp': 28,
    'ac': 18,
    'nivel': 3,
    'xp': 0,
    'initiative': 10,
    'att': 'Golpe +7 (1d8+1 eléctrico)',
    'movs': 'Descarga Mayor (2d4 eléctrico); Cuerpo Eléctrico'
  },
  {
    'name': 'Elemental de Rayo Grande',
    'type': 'Elemental',
    'hp': 60,
    'ac': 20,
    'nivel': 5,
    'xp': 0,
    'initiative': 12,
    'att': 'Golpe +12 (2d6+4 eléctrico)',
    'movs': 'Tormenta Eléctrica (área 15ft, 3d6 eléctrico); Cuerpo Eléctrico'
  },
  {
    'name': 'Elemental de Rayo Enorme',
    'type': 'Elemental',
    'hp': 100,
    'ac': 22,
    'nivel': 9,
    'xp': 0,
    'initiative': 14,
    'att': 'Golpe +18 (2d8+7 eléctrico)',
    'movs': 'Tormenta Eléctrica Mayor (área 20ft, 4d6 eléctrico); Cuerpo Eléctrico'
  },
  {
    'name': 'Elemental de Rayo Colosal',
    'type': 'Elemental',
    'hp': 160,
    'ac': 26,
    'nivel': 13,
    'xp': 0,
    'initiative': 16,
    'att': 'Golpe +26 (4d6+10 eléctrico)',
    'movs': 'Tormenta Eléctrica Cataclísmica (área 30ft, 8d6 eléctrico); Cuerpo Eléctrico Cataclísmico'
  },
  // Elementales de Arena
  {
    'name': 'Elemental de Arena Pequeño',
    'type': 'Elemental',
    'hp': 13,
    'ac': 16,
    'nivel': 1,
    'xp': 0,
    'initiative': 3,
    'att': 'Golpe +4 (1d6 cortante)',
    'movs': 'Cegar (1 turno); Forma Arenosa (ignora terreno difícil)'
  },
  {
    'name': 'Elemental de Arena Mediano',
    'type': 'Elemental',
    'hp': 30,
    'ac': 17,
    'nivel': 3,
    'xp': 0,
    'initiative': 5,
    'att': 'Golpe +7 (1d8+1 cortante)',
    'movs': 'Cegar Mayor (2 turnos); Forma Arenosa'
  },
  {
    'name': 'Elemental de Arena Grande',
    'type': 'Elemental',
    'hp': 62,
    'ac': 19,
    'nivel': 5,
    'xp': 0,
    'initiative': 7,
    'att': 'Golpe +12 (2d6+4 cortante)',
    'movs': 'Tormenta de Arena (área 15ft, 3d6 cortante); Forma Arenosa'
  },
  {
    'name': 'Elemental de Arena Enorme',
    'type': 'Elemental',
    'hp': 98,
    'ac': 21,
    'nivel': 9,
    'xp': 0,
    'initiative': 9,
    'att': 'Golpe +18 (2d8+7 cortante)',
    'movs': 'Tormenta de Arena Mayor (área 20ft, 4d6 cortante); Forma Arenosa'
  },
  {
    'name': 'Elemental de Arena Colosal',
    'type': 'Elemental',
    'hp': 155,
    'ac': 25,
    'nivel': 13,
    'xp': 0,
    'initiative': 11,
    'att': 'Golpe +26 (4d6+10 cortante)',
    'movs': 'Tormenta de Arena Cataclísmica (área 30ft, 8d6 cortante); Forma Arenosa Cataclísmica'
  },
  // Elementales de Humo
  {
    'name': 'Elemental de Humo Pequeño',
    'type': 'Elemental',
    'hp': 10,
    'ac': 15,
    'nivel': 1,
    'xp': 0,
    'initiative': 4,
    'att': 'Golpe +4 (1d6 asfixia)',
    'movs': 'Nube de Humo (oculta 10ft); Asfixia Menor (reduce acciones)'
  },
  {
    'name': 'Elemental de Humo Mediano',
    'type': 'Elemental',
    'hp': 24,
    'ac': 16,
    'nivel': 3,
    'xp': 0,
    'initiative': 6,
    'att': 'Golpe +7 (1d8+1 asfixia)',
    'movs': 'Nube de Humo Mayor (oculta 20ft); Asfixia'
  },
  {
    'name': 'Elemental de Humo Grande',
    'type': 'Elemental',
    'hp': 50,
    'ac': 18,
    'nivel': 5,
    'xp': 0,
    'initiative': 8,
    'att': 'Golpe +12 (2d6+4 asfixia)',
    'movs': 'Nube de Humo Total (oculta 30ft); Asfixia Mayor (reduce acciones)'
  },
  {
    'name': 'Elemental de Humo Enorme',
    'type': 'Elemental',
    'hp': 80,
    'ac': 20,
    'nivel': 9,
    'xp': 0,
    'initiative': 10,
    'att': 'Golpe +18 (2d8+7 asfixia)',
    'movs': 'Nube de Humo Absoluta (oculta 40ft); Asfixia Cataclísmica'
  },
  {
    'name': 'Elemental de Humo Colosal',
    'type': 'Elemental',
    'hp': 130,
    'ac': 24,
    'nivel': 13,
    'xp': 0,
    'initiative': 12,
    'att': 'Golpe +26 (4d6+10 asfixia)',
    'movs': 'Nube de Humo Cataclísmica (oculta 60ft); Asfixia Cataclísmica'
  },
  // Gremlins inventados
  {
    'name': 'Gremlin Saboteador',
    'hp': 85,
    'ac': 21,
    'nivel': 10,
    'xp': 0,
    'initiative': 7,
    'att': 'Daga oxidada +14 (1d6+4)',
    'movs': 'Sabotaje (desactiva trampas y puertas); Esquiva ágil',
    'type': 'Gremlin'
  },
  {
    'name': 'Gremlin Ilusionista',
    'hp': 70,
    'ac': 22,
    'nivel': 10,
    'xp': 0,
    'initiative': 8,
    'att': 'Bastón ilusorio +12 (1d6+2 psíquico)',
    'movs': 'Invisibilidad menor; Imagen múltiple',
    'type': 'Gremlin'
  },
  {
    'name': 'Gremlin Chispeante',
    'hp': 78,
    'ac': 20,
    'nivel': 11,
    'xp': 9600,
    'initiative': 10,
    'att': 'Toque eléctrico +15 (1d8+3 eléctrico)',
    'movs': 'Descarga menor (aturde 1 turno); Salto relámpago',
    'type': 'Gremlin'
  },
  {
    'name': 'Gremlin Alquimista',
    'hp': 90,
    'ac': 19,
    'nivel': 11,
    'xp': 9600,
    'initiative': 6,
    'att': 'Bomba improvisada +13 (2d6+2 fuego/ácido)',
    'movs': 'Lanzar poción (efecto aleatorio); Resistencia a venenos',
    'type': 'Gremlin'
  },
  {
    'name': 'Gremlin Sombrío',
    'hp': 72,
    'ac': 23,
    'nivel': 10,
    'xp': 0,
    'initiative': 9,
    'att': 'Garra sombría +14 (1d8+4 necrótico)',
    'movs': 'Paso sombrío (teleporta 10ft); Oscuridad menor',
    'type': 'Gremlin'
  },
  {
    'name': 'Gremlin de las Cavernas',
    'hp': 100,
    'ac': 20,
    'nivel': 12,
    'xp': 12800,
    'initiative': 5,
    'att': 'Maza de hueso +16 (2d6+5)',
    'movs': 'Excavar rápido; Grito ensordecedor',
    'type': 'Gremlin'
  },
  {
    'name': 'Gremlin Chamán',
    'hp': 80,
    'ac': 21,
    'nivel': 11,
    'xp': 9600,
    'initiative': 8,
    'att': 'Báculo rúnico +13 (1d8+3 mágico)',
    'movs': 'Curación menor; Maldición menor',
    'type': 'Gremlin'
  },
  {
    'name': 'Gremlin Montaraz',
    'hp': 88,
    'ac': 22,
    'nivel': 12,
    'xp': 12800,
    'initiative': 11,
    'att': 'Lanza corta +17 (1d6+6)',
    'movs': 'Emboscada; Trampa improvisada',
    'type': 'Gremlin'
  },
  {
    'name': 'Gremlin Gunslinger Torpe',
    'hp': 75,
    'ac': 19,
    'nivel': 11,
    'xp': 9600,
    'initiative': 12,
    'att': 'Pistola oxidada +10 (1d8+2, se rompe con 1-3)',
    'movs': 'Disparo accidental (puede herirse a sí mismo); Recarga lenta',
    'type': 'Gremlin'
  },
  {
    'name': 'Gremlin Bromista',
    'hp': 68,
    'ac': 21,
    'nivel': 10,
    'xp': 0,
    'initiative': 13,
    'att': 'Saco de trucos +15 (1d4+4, efecto aleatorio)',
    'movs': 'Truco molesto (aturde o desarma); Risa contagiosa',
    'type': 'Gremlin'
  },
  {
    'name': 'Onmyoji',
    'hp': 65,
    'ac': 18,
    'nivel': 11,
    'xp': 0,
    'initiative': 7,
    'att': 'Qstaff +2, (1d6+2)',
    'movs': 'Fireball, Dispell Magic, Mirror image, Shield, Scorching Ray, Magic Missile',
    'type': 'Japonés'
  },
  {
    'name': 'Samurai de Tokyo',
    'hp': 84,
    'ac': 21,
    'nivel': 11,
    'xp': 0,
    'initiative': 7,
    'att': 'Katana +4 (1d8+4)',
    'movs': 'Charge, Power Attack, Challenge',
    'type': 'Japonés'
  },
  {
    'name': 'Ninja de Kyoto',
    'hp': 70,
    'ac': 20,
    'nivel': 10,
    'xp': 0,
    'initiative': 9,
    'att': 'Wakizashi +7 (1d6+4)',
    'movs': 'Cloak of Shadows, Evasion, Shadow Step',
    'type': 'Japonés'
  },
  {
    'name': 'Kitsune Hechicero',
    'hp': 60,
    'ac': 18,
    'nivel': 11,
    'xp': 0,
    'initiative': 10,
    'att': 'Foxfire +2 (1d6+2 fire)',
    'movs': 'Illusion, Charm Person, Invisibility',
    'type': 'Japonés'
  },
  {
  "name": "Campeón Forjado en Sangre",
  "hp": 58,
  "ac": 19,
  "nivel": 5,
  "xp": 1600,
  "initiative": 1,
  "att": "Gran Hacha +10 (1d12+7)",
  "movs": "Aura de Miedo (enemigos a 10ft deben salvar Vol o quedan estremecidos); Grito de Guerra",
  "type": "Coreano"
},
{
  "name": "Soldado Forjado en Sangre",
  "hp": 32,
  "ac": 17,
  "nivel": 3,
  "xp": 800,
  "initiative": 1,
  "att": "Espada Larga +6 (1d8+3)",
  "movs": "Ferocidad (sigue luchando 1 asalto con PV negativos); Formación de Escudos",
  "type": "Coreano"
},
{
  "name": "General de Goguryeo",
  "hp": 76,
  "ac": 20,
  "nivel": 6,
  "xp": 2400,
  "initiative": 2,
  "att": "Gran Espada Maestra +12/+7 (2d6+8)",
  "movs": "Liderazgo (aliados ganan +1 a salvaciones); Voluntad de Hierro; Hender",
  "type": "Coreano"
},
{
  "name": "Manifestación Corrupta del Río",
  "hp": 42,
  "ac": 17,
  "nivel": 4,
  "xp": 1200,
  "initiative": 2,
  "att": "Golpetazo de Lodo +7 (1d6+4 más Presa)",
  "movs": "Amorfo; Agarrón de Lodo (inmoviliza al enemigo apresado); Oculto en el agua",
  "type": "Coreano"
},
{
  "name": "Espíritu del Río Sungari (Corrupto)",
  "hp": 84,
  "ac": 20,
  "nivel": 7,
  "xp": 3200,
  "initiative": 3,
  "att": "2 Golpes de Ola +11 (2d8+6)",
  "movs": "Vórtice (atrae a todos en 30ft al agua); RD 5/magia; Maestría Acuática",
  "type": "Coreano"
},
{
  "name": "Lugarteniente del Susurrante",
  "hp": 45,
  "ac": 18,
  "nivel": 5,
  "xp": 1600,
  "initiative": 4,
  "att": "Daga Envenenada +7 (1d4+2 más veneno) o Rayo debilitador",
  "movs": "Lanzamiento de Conjuros (Maldecir, Dormir); Invisibilidad; Sigilo experto",
  "type": "Coreano"
},
{
  "name": "Señor de la Guerra Khitan Bortei",
  "hp": 95,
  "ac": 18,
  "nivel": 7,
  "xp": 3200,
  "initiative": 3,
  "att": "Gran Hacha en Furia +13/+8 (1d12+12)",
  "movs": "Furia (más fuerte y resistente al ser herido); Presencia Aterradora; Carga brutal",
  "type": "Coreano"
},
{
  "name": "Guardia de Élite Khitan",
  "hp": 40,
  "ac": 18,
  "nivel": 4,
  "xp": 1200,
  "initiative": 3,
  "att": "Arco largo compuesto +8 (1d8+3)",
  "movs": "Combate Montado; Disparo Preciso; Experto Jinete",
  "type": "Coreano"
},
{
  "name": "Constructo de Hierro Maldito",
  "hp": 50,
  "ac": 19,
  "nivel": 5,
  "xp": 1600,
  "initiative": -1,
  "att": "2 Golpetazos +9 (1d8+5)",
  "movs": "Rasgos de Constructo (inmune a mente, veneno, etc.); RD 5/adamantita; Pulso Magnético (desarma armas de metal)",
  "type": "Coreano"
},
{
  "name": "Guardia de la Forja de Almas",
  "hp": 68,
  "ac": 20,
  "nivel": 6,
  "xp": 2400,
  "initiative": 1,
  "att": "Espada Larga Flamígera +11/+6 (1d8+5 más 1d6 fuego)",
  "movs": "Inmune al Fuego; Resistencia a Conjuros; Aura de Pavor (similar a Aura de Miedo)",
  "type": "Coreano"
},
{
  "name": "El Susurrante de Hierro",
  "hp": 92,
  "ac": 22,
  "nivel": 8,
  "xp": 4800,
  "initiative": 5,
  "att": "Toque de Corrupción +10 (5d6 daño negativo) o conjuros",
  "movs": "Conjuros (Dominar Persona, Confusión); Viaje Sombrío (teletransporte); Mente Laberíntica (fuerza salvación de Vol para poder atacarle)",
  "type": "Coreano"
},
{
  "name": "Lobo de la Estepa Corrupto",
  "hp": 18,
  "ac": 15,
  "nivel": 2,
  "xp": 600,
  "initiative": 2,
  "att": "Mordisco +4 (1d6+2 más Derribo)",
  "movs": "Tácticas de Manada (+2 al atacar si un aliado flanquea); Aullido Inquietante",
  "type": "Coreano"
},
{
  "name": "Explorador de Goguryeo",
  "hp": 22,
  "ac": 16,
  "nivel": 2,
  "xp": 600,
  "initiative": 3,
  "att": "Arco corto +5 (1d6) o Espada corta +4 (1d6+1)",
  "movs": "Ataque Furtivo +1d6; Sigilo experto; Trampero (puede colocar trampas simples)",
  "type": "Coreano"
},
{
  "name": "Esqueleto Resentido",
  "hp": 16,
  "ac": 16,
  "nivel": 2,
  "xp": 600,
  "initiative": 2,
  "att": "Cimitarra rota +3 (1d6+1)",
  "movs": "RD 5/contundente; Inmune a frío y efectos mentales; Ráfaga de Golpes (dos ataques con penalizador)",
  "type": "Coreano"
},
{
  "name": "Dokkabei Bromista",
  "hp": 25,
  "ac": 15,
  "nivel": 3,
  "xp": 800,
  "initiative": 2,
  "att": "Garrote de Madera +5 (1d8+2)",
  "movs": "Conjuros (Sonido Fantasma, Grasa); Invisibilidad a voluntad; Robar objeto",
  "type": "Coreano"
},
{
  "name": "Soldado de la Dinastía Tang",
  "hp": 30,
  "ac": 18,
  "nivel": 3,
  "xp": 800,
  "initiative": 1,
  "att": "Jian (espada) +6 (1d8+2)",
  "movs": "Formación de Muro de Escudos (+2 a la CA si está junto a un aliado); Disciplina militar",
  "type": "Coreano"
},
{
  "name": "Tigre de Manchuria Sombrío",
  "hp": 52,
  "ac": 17,
  "nivel": 5,
  "xp": 1600,
  "initiative": 4,
  "att": "2 Garras +9 (1d6+5), Mordisco +9 (1d10+5)",
  "movs": "Abrazo; Salto; Ocultarse en las Sombras (sigilo mejorado en penumbra)",
  "type": "Coreano"
},
{
  "name": "Místico Desterrado de Silla",
  "hp": 41,
  "ac": 16,
  "nivel": 5,
  "xp": 1600,
  "initiative": 2,
  "att": "Toque de la Putrefacción +3 (3d6) o conjuros",
  "movs": "Conjuros (Ceguera, Rayo de Debilitamiento); Canalizar energía negativa; Aura de Repulsión",
  "type": "Coreano"
},
{
  "name": "Espíritu del Bosque Vengativo",
  "hp": 60,
  "ac": 19,
  "nivel": 6,
  "xp": 2400,
  "initiative": 3,
  "att": "Golpetazo de Rama +10 (1d8+6)",
  "movs": "RD 10/hierro frío; Animar Árbol; Enmarañar a voluntad",
  "type": "Coreano"
},
{
  "name": "Asesino de la Sombra Yemaek",
  "hp": 55,
  "ac": 19,
  "nivel": 6,
  "xp": 2400,
  "initiative": 5,
  "att": "2 Dagas envenenadas +9/+9 (1d4+3 más veneno debilitante)",
  "movs": "Ataque Furtivo +3d6; Paso Sombrío (teletransporte corto en sombras); Evasión",
  "type": "Coreano"
},
{
  "name": "Dokkabei Herrero",
  "hp": 78,
  "ac": 18,
  "nivel": 6,
  "xp": 2400,
  "initiative": 1,
  "att": "Martillo de Guerra +12 (1d10+8)",
  "movs": "Romper Arma; Pisotón (onda de choque aturdidora); Piel de Hierro (RD 5/magia)",
  "type": "Coreano"
},
{
  "name": "Guardián Haetae de Piedra",
  "hp": 85,
  "ac": 22,
  "nivel": 7,
  "xp": 3200,
  "initiative": 0,
  "att": "Mordisco +13 (2d8+7)",
  "movs": "Rasgos de Constructo; Mirada Petrificante (Salv. Fortaleza CD 18); Piel de Piedra (RD 10/adamantita)",
  "type": "Coreano"
},
{
  "name": "Imugi Menor (Serpiente Dragón)",
  "hp": 105,
  "ac": 20,
  "nivel": 7,
  "xp": 3200,
  "initiative": 4,
  "att": "Mordisco +14 (2d6+8 más Presa), Constricción (2d6+8)",
  "movs": "Aliento de Niebla (crea Niebla de Obscurecimiento); Anfibio; Regeneración 5 (excepto frío)",
  "type": "Coreano"
},
{
  "name": "Gigante de las Montañas (Yaksa)",
  "hp": 114,
  "ac": 19,
  "nivel": 8,
  "xp": 4800,
  "initiative": -1,
  "att": "Gran Garrote +15/+10 (2d10+10) o Arrojar Roca +7 (2d8+10)",
  "movs": "Pisotón poderoso; Resistencia a conjuros; Regeneración 5",
  "type": "Coreano"
},
{
  "name": "Kumiho Engañosa (Zorro de 9 colas)",
  "hp": 88,
  "ac": 21,
  "nivel": 8,
  "xp": 4800,
  "initiative": 6,
  "att": "Mordisco +11 (1d8+3) o conjuros",
  "movs": "Lanzamiento de conjuros (Dominar Persona, Sugestión); Cambio de Forma; Drenar esencia vital",
  "type": "Coreano"
},
{
  "name": "Mongol Raider",
  "hp": 70,
  "ac": 19,
  "nivel": 8,
  "xp": 4800,
  "initiative": 3,
  "att": "Greataxe +12 (1d12+11)",
  "movs": "Rage (+2 daño); Carga poderosa",
  "type": "Mongoles"
},
{
  "name": "Shugenja Aprendiz",
  "hp": 45,
  "ac": 16,
  "nivel": 7,
  "xp": 3200,
  "initiative": 2,
  "att": "Scorching Ray (4d6 fuego); Fireball (7d6 fuego)",
  "movs": "Lanzamiento de Conjuros; Vuelo (Fly)",
  "type": "Mongoles"
},
{
  "name": "Clérigo de Tengri",
  "hp": 68,
  "ac": 20,
  "nivel": 8,
  "xp": 4800,
  "initiative": 1,
  "att": "Flame Strike (8d6); Spiritual Weapon (1d8+4)",
  "movs": "Channel Negative Energy (4d6); Conjuros divinos",
  "type": "Mongoles"
},
{
  "name": "Guardia Élite Mongol",
  "hp": 95,
  "ac": 23,
  "nivel": 10,
  "xp": 9600,
  "initiative": 2,
  "att": "Bardiche +17/+12 (1d10+15)",
  "movs": "Formación Táctica (bonos con aliados); Muro de Escudos; Hender",
  "type": "Mongoles"
},
{
  "name": "General Mongol",
  "hp": 195,
  "ac": 28,
  "nivel": 15,
  "xp": 51200,
  "initiative": 3,
  "att": "Katana Pesada +24/+19/+14 (2d6+24)",
  "movs": "Banner of War (estandarte de guerra); Carga Montada Letal; Liderazgo de Ejército",
  "type": "Mongoles"
},
{
  "name": "Shaman Tengri",
  "hp": 180,
  "ac": 22,
  "nivel": 15,
  "xp": 51200,
  "initiative": 4,
  "att": "Flame Strike (15d6); Aura de Tormenta (daño elemental)",
  "movs": "Control Weather; Forma Salvaje Mayor; Conjuros de Druida",
  "type": "Mongoles"
},
{
  "name": "Gunslinger Yuan",
  "hp": 122,
  "ac": 23,
  "nivel": 13,
  "xp": 25600,
  "initiative": 6,
  "att": "Pistola +18/+13/+8 (1d8+9)",
  "movs": "Rapid Shot; Targeting Shot; Grit (puntos de hazaña)",
  "type": "Mongoles"
},
{
  "name": "Asesino de la Sombra Mongol",
  "hp": 85,
  "ac": 21,
  "nivel": 11,
  "xp": 9600,
  "initiative": 7,
  "att": "2 Dagas +15/+10 (1d4+6 más veneno)",
  "movs": "Paso Sombrío; Ataque Furtivo +4d6; Evasión",
  "type": "Mongoles"
},
{  "name": "Chamán de la Tormenta",
  "hp": 110,
  "ac": 20,
  "nivel": 12,
  "xp": 19200,
  "initiative": 5,
  "att": "Lightning Bolt (10d6); Call Lightning (6d6)",
  "movs": "Channel Energy (5d6); Conjuros de Clérigo y Druida",
  "type": "Mongoles"
},
{
  "name": "Soldado Élite Mongol (Final)",
  "hp": 110,
  "ac": 23,
  "nivel": 12,
  "xp": 19200,
  "initiative": 2,
  "att": "Bardiche +18/+13/+8 (1d10+20)",
  "movs": "Formación Cerrada (bono de CA y ataque masivo); Voluntad de Hierro",
  "type": "Mongoles"
}
];